apiVersion: v1
kind: Service
metadata:
  name: future-sales-prediction
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: future-sales-prediction
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: future-sales-prediction
spec:
  backend:
    serviceName: future-sales-prediction
    servicePort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: future-sales-prediction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: future-sales-prediction
  template:
    metadata:
      labels:
        app: future-sales-prediction
    spec:
      volumes:

      containers:
      - name: future-sales-prediction
        image: FUTURE_SALES_PREDICTION_IMAGE
        env:
        - name: PREDICTIONS_URI
          value: "."
        - name: MODEL_NAME
          value: "model.pkl"
        - name: PROC_FILENAME
          value: "data-proc-obj.pkl"
        ports:
          - containerPort: 5000
        livenessProbe:      # Used by deployment controller
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:     # Used by Ingress/GCLB
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          limits:
            memory: 1024Mi
          requests:
            memory: 256Mi